name: ci

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed

env:
  # Set the initial version
  INITIAL_VERSION: 1
  LATEST_TAG: quadribello/ml_app:${{ github.run_number }}-${{ env.INITIAL_VERSION }}

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine the new version
        id: version
        run: echo ::set-output name=VERSION::${{ env.INITIAL_VERSION + 1 }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quadribello/ml_app:${{ github.run_number }}-${{ steps.version.outputs.VERSION }}
